### ISSUE TITLE
Question about the new definition std :: jthread

### ISSUE THREAD

**Issue by Jamaika1** [josuttis/jthread#37]
How different is the std::thread from std::jthread?
Does it make sense to change definitions for c++20?
Is std::jthread only under c++20?
I was able to compile std::jthread under c++17. Is it compatible with mingw.thread.h?

**Comment by josuttis** [comment]
std::jthread is backward compatible in a way that all functions of std::thread are still supported with the difference of the behavior of the destructor and assignment operator (performing a request_stop() and join() if still joinable).

What do you mean by "Does it make sense to change definitions for c++20"?
If you mean: "Should I switch to std::jthread?" then usually clearly yes.

std::jthread was standardized for C++20 and is not available under C++17.
You could use the code here for earlier C++ versions, but the extensions to condition variables need modifications of their classes. That's why we use a different CV class/namespace here.
If you only need the improved thread API, then you usually can use the code here earlier.

**Comment by Jamaika1** [comment]
Thanks for the answer
Recently I was compiling under gcc 11.0 with c++17 with your libraries. The openexr codec needs modifications mingw under Windows. Successfully replaced std :: thread with std :: jthread. However, I am wondering in gcc 11.0 under Windows. Does for c++20 need modifications of classes?
https://github.com/AcademySoftwareFoundation/openexr/pull/851/commits/59608240ed175a17f0fec9fc7e9682a6a6d75754

**Comment by josuttis** [comment]
What do you mean by "Does for c++20 need modifications of classes?" ?
Which classes?

**Comment by Jamaika1** [comment]
Generally. Who is this creative commons licensed jthread library addressed to?
For gcc, the <thread> function has jthread inside, and in c ++ 20 it doesn't need jthread.hpp. Is there something more here than in compilers?
